-- =====================================================================
-- 40 — AoL: los ids del esquema histórico no se generaban solos
-- =====================================================================
-- Las tablas del histórico de AoL (cohorte, proyecto, estudiante, medicion,
-- criterio) se crearon en la migración 36 poblándolas desde los Excel con los
-- ids escritos a mano. La columna quedó NOT NULL pero SIN default ni identity.
--
-- Consecuencia: al firmar una calificación desde la plataforma, el backend
-- inserta en esas tablas sin `id` y Postgres rechaza la fila con
--   null value in column "id" ... violates not-null constraint
-- Como `medicion` se inserta SIEMPRE, ninguna calificación podía guardarse:
-- el profesor aprobaba y no quedaba nada (reportado por JMV el 28/jul/2026).
--
-- Arreglo: convertir esos ids en IDENTITY, arrancando la secuencia después del
-- máximo actual para no chocar con las filas ya importadas. Es idempotente:
-- si la columna ya es identity, no hace nada.
-- =====================================================================

DO $$
DECLARE
  t   text;
  sig bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY['cohorte', 'proyecto', 'estudiante', 'medicion', 'criterio']
  LOOP
    -- Ya es identity (o tiene default): no tocar.
    IF EXISTS (
      SELECT 1 FROM pg_attribute a
      JOIN pg_class c ON c.oid = a.attrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace AND n.nspname = 'public'
      WHERE c.relname = t AND a.attname = 'id' AND a.attidentity <> ''
    ) THEN
      RAISE NOTICE '%.id ya es identity, se omite', t;
      CONTINUE;
    END IF;

    EXECUTE format('SELECT coalesce(max(id), 0) + 1 FROM public.%I', t) INTO sig;
    EXECUTE format(
      'ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      t, sig
    );
    RAISE NOTICE '%.id -> identity arrancando en %', t, sig;
  END LOOP;
END $$;
